services:
  frontend:
    build: 
      context: ./frontend
      target: development
      args:
        - NODE_ENV=development
    ports:
      - "3000:5173"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/index.html:/app/index.html
      - ./frontend/public:/app/public
      - ./frontend/vite.config.ts:/app/vite.config.ts
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    depends_on:
      - compiler

  compiler:
    build: ./compiler
    ports:
      - "3002:3002" 