
services:
  frontend:
    build: ./frontend
    image: my-compiler-frontend
    container_name: frontend
    # The frontend is served by nginx on port 80 inside the container
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    image: my-compiler-backend
    container_name: backend
    # Backend runs on port 3001
    ports:
      - "3001:3001"
    environment:
      # Backend will call the compiler service by this hostname and port
      COMPILER_URL: "http://compiler:3002"
    depends_on:
      - compiler

  compiler:
    build: ./compiler
    image: my-compiler-service
    container_name: compiler
    # Compiler service runs on port 3002
    ports:
      - "3002:3002"
