services:
  frontend:
    build: 
      context: ./frontend
      args:
        - NODE_ENV=development
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    depends_on:
      - compiler

  compiler:
    build: ./compiler
    ports:
      - "3002:3002" 