services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - compiler
    restart: unless-stopped

  compiler:
    build: ./compiler
    ports:
      - "3002:3002"
    restart: unless-stopped
