FROM node:18-alpine

# Create and set working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json (if present) and install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the code
COPY . .


EXPOSE 3001

# Set the default command to start the server
CMD ["npm", "start"]
