name: Deploy to DigitalOcean
on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Deploy to Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd /home/deploy/online-gcc-compiler || exit 1
            git pull origin master
            if [ ! -f "docker-compose.prod.yml" ]; then
              echo "docker-compose.prod.yml not found"
              exit 1
            fi
            docker compose -f docker-compose.prod.yml up -d --build
            docker system prune -af