name: Deploy to DigitalOcean
on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Deploy to Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            # Ensure the project directory exists
            if [ ! -d "/home/deploy/online-gcc-compiler" ]; then
              echo "Directory /home/deploy/online-gcc-compiler does not exist."
              exit 1
            fi

            # Navigate to the project directory
            cd /home/deploy/online-gcc-compiler

            # Ensure .env.production exists
            if [ ! -f ".env.production" ]; then
              echo ".env.production file is missing."
              exit 1
            fi

            # Pull latest changes
            git pull origin master

            # Deploy the application
            docker compose -f docker-compose.prod.yml up -d --build

            # Clean up unused Docker resources
            docker system prune -af