name: Deploy to DigitalOcean
on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            if [ ! -d "/home/deploy/online-gcc-compiler" ]; then
              echo "Directory /home/deploy/online-gcc-compiler does not exist. Cloning repository."
              git clone https://github.com/YanivGabay/Online-HAC-Compiler.git /home/deploy/online-gcc-compiler
            fi
            cd /home/deploy/online-gcc-compiler
            git pull origin master
            if [ ! -f "docker-compose.prod.yml" ]; then
              echo "File docker-compose.prod.yml is missing."
              exit 1
            fi
            docker compose -f docker-compose.prod.yml up -d --build
            docker system prune -af